CREATE TABLE booking_details (
    id INT PRIMARY KEY AUTO_INCREMENT,
    booking_id INTEGER NULL REFERENCES bookings(id) ON DELETE CASCADE,
    seat_id INTEGER NULL REFERENCES seats(id) ON DELETE CASCADE,
    price DECIMAL(10,2) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
